const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Touch,
		C3.Plugins.Text,
		C3.Plugins.Browser,
		C3.Plugins.Audio,
		C3.Plugins.progressbar,
		C3.Plugins.shadowlight,
		C3.Plugins.Particles,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Touch.Exps.TouchCount,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Touch.Cnds.OnDoubleTapGestureObject,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.PickNth,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Particles.Acts.SetPosToObject,
		C3.Plugins.Particles.Acts.SetSpeedRandomiser,
		C3.Plugins.Particles.Acts.SetEffect,
		C3.Plugins.Particles.Acts.SetGrowRate,
		C3.Plugins.Text.Acts.SetFontSize,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Plugins.Text.Acts.SetFontFace,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Acts.Wait
	];
};
self.C3_JsPropNameTable = [
	{Map: 0},
	{IsMarked: 0},
	{Değişken1: 0},
	{Target: 0},
	{Dokun: 0},
	{ScoreText: 0},
	{Tarayıcı: 0},
	{Sprite: 0},
	{Marked: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{BaslaTarget: 0},
	{Sprite5: 0},
	{Ses: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{Sprite12: 0},
	{Sprite13: 0},
	{Sprite10: 0},
	{yonergegit: 0},
	{yonergecikis: 0},
	{Sprite11: 0},
	{Sprite14: 0},
	{Sprite4: 0},
	{anasayfabuton: 0},
	{Sprite15: 0},
	{gecisekran: 0},
	{cubuk1: 0},
	{cubuk2: 0},
	{cubuk3: 0},
	{İlerlemeÇubuğu: 0},
	{Sprite16: 0},
	{Sprite17: 0},
	{Sprite18: 0},
	{Sprite19: 0},
	{efekt: 0},
	{GölgeIşığı: 0},
	{isilti: 0},
	{Partiküller: 0},
	{geriTarget: 0},
	{Sprite20: 0},
	{sure: 0},
	{Sprite21: 0},
	{Sprite22: 0},
	{sesackapa: 0},
	{Sprite23: 0},
	{Altın: 0},
	{Sprite24: 0},
	{Sprite25: 0},
	{IsDragging: 0},
	{DeltaX: 0},
	{DeltaY: 0},
	{Puan: 0},
	{Score: 0},
	{Süre: 0}
];

self.InstanceType = {
	Map: class extends self.ISpriteInstance {},
	Target: class extends self.ISpriteInstance {},
	Dokun: class extends self.IInstance {},
	ScoreText: class extends self.ITextInstance {},
	Tarayıcı: class extends self.IInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Marked: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	BaslaTarget: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Ses: class extends self.IInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	yonergegit: class extends self.ISpriteInstance {},
	yonergecikis: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	anasayfabuton: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	gecisekran: class extends self.ISpriteInstance {},
	cubuk1: class extends self.ISpriteInstance {},
	cubuk2: class extends self.ISpriteInstance {},
	cubuk3: class extends self.ISpriteInstance {},
	İlerlemeÇubuğu: class extends self.IProgressBarInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	efekt: class extends self.ISpriteInstance {},
	GölgeIşığı: class extends self.IShadowLightInstance {},
	isilti: class extends self.ISpriteInstance {},
	Partiküller: class extends self.IParticlesInstance {},
	geriTarget: class extends self.ISpriteInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	sure: class extends self.ITextInstance {},
	Sprite21: class extends self.ISpriteInstance {},
	Sprite22: class extends self.ISpriteInstance {},
	sesackapa: class extends self.ISpriteInstance {},
	Sprite23: class extends self.ISpriteInstance {},
	Altın: class extends self.ISpriteInstance {},
	Sprite24: class extends self.ISpriteInstance {},
	Sprite25: class extends self.ISpriteInstance {}
}