const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Touch,
		C3.Plugins.Text,
		C3.Plugins.Browser,
		C3.Plugins.Audio,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Touch.Exps.TouchCount,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Touch.Cnds.OnDoubleTapGestureObject,
		C3.Plugins.System.Cnds.PickNth,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetFontSize,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Acts.GoToLayoutByName
	];
};
self.C3_JsPropNameTable = [
	{Map: 0},
	{IsMarked: 0},
	{Değişken1: 0},
	{Target: 0},
	{Dokun: 0},
	{ScoreText: 0},
	{Tarayıcı: 0},
	{Sprite: 0},
	{Marked: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{BaslaTarget: 0},
	{Sprite5: 0},
	{Ses: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{Sprite12: 0},
	{Sprite13: 0},
	{Sprite10: 0},
	{yonergegit: 0},
	{yonergecikis: 0},
	{Sprite11: 0},
	{Sprite14: 0},
	{Sprite4: 0},
	{anasayfabuton: 0},
	{IsDragging: 0},
	{DeltaX: 0},
	{DeltaY: 0},
	{TouchLastX: 0},
	{TouchLastY: 0},
	{Puan: 0},
	{Score: 0},
	{IsDragging2: 0},
	{DeltaX2: 0},
	{DeltaY2: 0},
	{Marked2: 0},
	{TouchLastX2: 0},
	{TouchLastY2: 0},
	{Puan2: 0},
	{Score2: 0}
];

self.InstanceType = {
	Map: class extends self.ISpriteInstance {},
	Target: class extends self.ISpriteInstance {},
	Dokun: class extends self.IInstance {},
	ScoreText: class extends self.ITextInstance {},
	Tarayıcı: class extends self.IInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Marked: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	BaslaTarget: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Ses: class extends self.IInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	yonergegit: class extends self.ISpriteInstance {},
	yonergecikis: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	anasayfabuton: class extends self.ISpriteInstance {}
}